### ISSUE TITLE
feature-request-HipMCL

### ISSUE THREAD

**Issue by sgordon007** [vinuesa/get_phylomarkers#1]
Can you guys add HipMCL as one of the clustering options?  [HipMCL](https://bitbucket.org/azadcse/hipmcl/wiki/Home)

best,  Sean

**Comment by eead-csic-compbio** [comment]
We will have a look, I can see source code is there, are there precompiled binaries for Linux and MacOS?

**Comment by sgordon007** [comment]
I don't know of precompiled binaries for it.

**Comment by vinuesa** [comment]
Hi Sean, thanks for your request. If integrated, it should go it should rather go into GET_HOMOLOGUES. GET_PHYLOMARKERS works downstream of the former.
