### ISSUE TITLE
ERROR! The expected output file sorted_aggregated_support_values4loci_ge70perc.tab was not produced, will exit now

### ISSUE THREAD

**Issue by TheCasualoooo** [vinuesa/get_phylomarkers#15]
Dear get_phylomarkers team,

These are my running codes:
get_homologues.pl -d gbk -t 12 -e -n 10
get_homologues.pl -d gbk -G -t 0 -o COG
get_homologues.pl -d gbk -M -t 0 -o OMCL

compare_clusters.pl -d ./COG/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algCOG_e0_,./OMCL2/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algOMCL_e0_,./gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_12taxa_algBDBH_e1_ -o core -t 30
compare_clusters.pl -d ./COG/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algCOG_e0_,./OMCL2/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algOMCL_e0_,./gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_12taxa_algBDBH_e1_ -o core -t 30 -n

and I get core, then
cd core
run_get_phylomarkers_pipeline.sh -R 1 -t DNA

finally I get error:
awk: fatal: cannot open file `sorted_aggregated_support_values4loci.tab' for reading (No such file or directory)
 >>> ERROR! The expected output file sorted_aggregated_support_values4loci_ge70perc.tab was not produced, will exit now!
 
 I dont know why, Is there a problem with my input file?
 
the attachment is my log.

I look forward to hearing from you.
[get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_27Sep23.log](https://github.com/vinuesa/get_phylomarkers/files/12735239/get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_27Sep23.log)
[run_get_phylomarkers_pipeline.log](https://github.com/vinuesa/get_phylomarkers/files/12735240/run_get_phylomarkers_pipeline.log)

**Comment by TheCasualoooo** [comment]
when I run compute_suppValStas_and_RF-dist.R

WARNING: ignoring environment value of R_HOME
also installing the dependency ‘Rcpp’

trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_1.0.11.tar.gz'
Content type 'application/x-gzip' length 2994004 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

trying URL 'https://cloud.r-project.org/src/contrib/ape_5.7-1.tar.gz'
Content type 'application/x-gzip' length 1577273 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/Rcpp’
ERROR: dependency ‘Rcpp’ is not available for package ‘ape’
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/ape’

The downloaded source packages are in
	‘/tmp/RtmpltCJZc/downloaded_packages’
also installing the dependencies ‘bitops’, ‘gtools’, ‘caTools’

trying URL 'https://cloud.r-project.org/src/contrib/bitops_1.0-7.tar.gz'
Content type 'application/x-gzip' length 10809 bytes (10 KB)
==================================================
downloaded 10 KB

trying URL 'https://cloud.r-project.org/src/contrib/gtools_3.9.4.tar.gz'
Content type 'application/x-gzip' length 240661 bytes (235 KB)
==================================================
downloaded 235 KB

trying URL 'https://cloud.r-project.org/src/contrib/caTools_1.18.2.tar.gz'
Content type 'application/x-gzip' length 64960 bytes (63 KB)
==================================================
downloaded 63 KB

trying URL 'https://cloud.r-project.org/src/contrib/gplots_3.1.3.tar.gz'
Content type 'application/x-gzip' length 520683 bytes (508 KB)
==================================================
downloaded 508 KB

* installing *source* package ‘bitops’ ...
** package ‘bitops’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/bitops’
* installing *source* package ‘gtools’ ...
** package ‘gtools’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/gtools’
ERROR: dependency ‘bitops’ is not available for package ‘caTools’
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/caTools’
ERROR: dependencies ‘gtools’, ‘caTools’ are not available for package ‘gplots’
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/gplots’

The downloaded source packages are in
	‘/tmp/RtmpltCJZc/downloaded_packages’
trying URL 'https://cloud.r-project.org/src/contrib/seqinr_4.2-30.tar.gz'
Content type 'application/x-gzip' length 3538250 bytes (3.4 MB)
==================================================
downloaded 3.4 MB

* installing *source* package ‘seqinr’ ...
** package ‘seqinr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
* removing ‘/project/wangjunlong/software/get_phylomarkers/lib/R/seqinr’

The downloaded source packages are in
	‘/tmp/RtmpltCJZc/downloaded_packages’
Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ape’
2: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘Rcpp’ had non-zero exit status
3: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘ape’ had non-zero exit status
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘gplots’
5: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘bitops’ had non-zero exit status
6: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘gtools’ had non-zero exit status
7: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘caTools’ had non-zero exit status
8: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘gplots’ had non-zero exit status
9: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘seqinr’
10: In install.packages(package, repos = REPOS, lib = LOCAL_LIB) :
  installation of package ‘seqinr’ had non-zero exit status
Error in library(pkg, character.only = T, quietly = T) : 
  there is no package called ‘plyr’
Execution halted

echo $R_LIBS_SITE
/mypath/to/get_phylomarkers/lib/R


How can I solve this problem？

**Comment by TheCasualoooo** [comment]
when I run compute_suppValStas_and_RF-dist.R, the display information is shown in the attachment

This is the location of the $R_LIBS_SITE
echo $R_LIBS_SITE
/path/to/get_phylomarkers/lib/R

I guess it could be a problem with R
How can I solve this problem ?
[R.log](https://github.com/vinuesa/get_phylomarkers/files/12737808/R.log)

**Comment by TheCasualoooo** [comment]
run_get_phylomarkers_pipeline.sh
Does this script have breakpoint continuation parameters?

**Comment by eead-csic-compbio** [comment]
Hi @TheCasualoooo , it does seem the installation of R package Rcpp is failing. You would have to sort that out in your system for this to work.
Another option is to use the Docker image of GET_PHYLOMARKERS with your core clusters, there are instructions for that at the [tutorial](https://vinuesa.github.io/get_phylomarkers/#get_phylomarkers-tutorial). 
Any other options @vinuesa ?

**Comment by TheCasualoooo** [comment]
Maybe my gcc version is too outdated? my version is 4.8, some packages require C (gcc) and C++ (g++) compilers to be installed.
I am trying to update gcc, and if it works, I will let you know, thank you!

**Comment by vinuesa** [comment]
> Dear get_phylomarkers team,
> 
> These are my running codes: get_homologues.pl -d gbk -t 12 -e -n 10 get_homologues.pl -d gbk -G -t 0 -o COG get_homologues.pl -d gbk -M -t 0 -o OMCL
> 
> compare_clusters.pl -d ./COG/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algCOG_e0_,./OMCL2/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algOMCL_e0_,./gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_12taxa_algBDBH_e1_ -o core -t 30 compare_clusters.pl -d ./COG/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algCOG_e0_,./OMCL2/gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_0taxa_algOMCL_e0_,./gbk_homologues/PararhizobiummangroviBGMRC6574T_f0_12taxa_algBDBH_e1_ -o core -t 30 -n
> 
> and I get core, then cd core run_get_phylomarkers_pipeline.sh -R 1 -t DNA
> 
> finally I get error: awk: fatal: cannot open file `sorted_aggregated_support_values4loci.tab' for reading (No such file or directory)
> 
> > > > ERROR! The expected output file sorted_aggregated_support_values4loci_ge70perc.tab was not produced, will exit now!
> 
> I dont know why, Is there a problem with my input file?
> 
> the attachment is my log.
> 
> I look forward to hearing from you. [get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_27Sep23.log](https://github.com/vinuesa/get_phylomarkers/files/12735239/get_phylomarkers_run_AIR1tDNA_k1.5_m0.7_Thigh_27Sep23.log) [run_get_phylomarkers_pipeline.log](https://github.com/vinuesa/get_phylomarkers/files/12735240/run_get_phylomarkers_pipeline.log)

Hi TheCasualoooo, there seems to be an issue with your get_homologues.pl and later compare_clusters.pl calls, as in the former you run 'get_homologues.pl -d gbk -t 12 -e -n 10' but are willing to compute a consensus core genome with -t 30 in the downstream compare_clusters.pl call. For the get_homologues run under the BDBH algorithm you should use -t X, where x is then number of genomes in your gbk directory. Hope this helps, cheers.
