### ISSUE TITLE
>>> ERROR: Input f?aed files do not contain the same number of strains and a single instance for each strain...

### ISSUE THREAD

**Issue by marlaux** [vinuesa/get_phylomarkers#16]
Hello
I couldn't find the guidance for this error in the manual and tutorials. Following the tutorial at https://vinuesa.github.io/get_phylomarkers/GET_PHYLOMARKERS_manual.html#get_phylomarkers-tutorial I assume that I did all right until the command run_get_phylomarkers_pipeline.sh -R 2 -t DNA.
I couldn't understand what I should do according to the error description. May someone help me, please? Thank you

My commands:
initial folder 'PlanktoPampPhylo_gbk': 5 references (NCBI) + 10 MAGs, all in gbff format (annotated using bakta)
then:
>get_homologues.pl -d PlanktoPampPhylo_gbk -t 15 -e -n 16
>get_homologues.pl -d PlanktoPampPhylo_gbk -G -t 0 -n 16
>get_homologues.pl -d PlanktoPampPhylo_gbk -M -t 0 -n 16
>compare_clusters.pl -d ./MetaPamp092015AG5bin6_f0_15taxa_algBDBH_e1_,\
          ./MetaPamp092015AG5bin6_f0_0taxa_algCOG_e0_,\
          ./MetaPamp092015AG5bin6_f0_0taxa_algOMCL_e0_ -o core_BCM -t 15 -n
>compare_clusters.pl -d ./MetaPamp092015AG5bin6_f0_15taxa_algBDBH_e1_,\
          ./MetaPamp092015AG5bin6_f0_0taxa_algCOG_e0_,\
          ./MetaPamp092015AG5bin6_f0_0taxa_algOMCL_e0_ -o core_BCM -t 15
>compare_clusters.pl -d ./MetaPamp092015AG5bin6_f0_0taxa_algCOG_e0_,\
          ./MetaPamp092015AG5bin6_f0_0taxa_algOMCL_e0_ -o pan_CM -n -m
>cd PlanktoPampPhylo_gbk_homologues/core_BCM
>find . -name '*.faa' | wc -l
4269
>find . -name '*.fna' | wc -l
4269
>run_get_phylomarkers_pipeline.sh -R 2 -t DNA
...
      1 >Bakta_PJECAB_20240_
      1 >Bakta_PJECAB_20245_
      1 >Bakta_PJECAB_20250_
      1 >Bakta_PJECAB_20255_
      1 >Bakta_PJECAB_20260_
      1 >Bakta_PJECAB_20265_
      1 >Bakta_PJECAB_20270_
   1423 >[Planktothrix_mougeotii_LEGE_06226]_LEGE_06226
   1423 >[Planktothrix_pseudagardhii]_No.713
   1423 >[Planktothrix_sp._FACHB-1365]_FACHB-1365
   1423 >[Planktothrix_tepida]_PCC9214
   1423 >[Planktothrix_tepida_PCC_9214]_

 >>> ERROR: Input f?aed files do not contain the same number of strains and a single instance for each strain...
         Please check input FASTA files as follows: 
         1. Revise the output above to make sure that all genomes have a strain assignation and the same number of associated sequences. 
              If not, add strain name manually to the corresponding fasta files or exclude them.
         2. Make sure that only one genome/gbk file is provided for each strain.     
         3. You may need to run get_homologues.pl with -e or compare_clusters.pl with -t NUM_OF_INPUT_GENOMES to get clusters of equal sizes
             Please check the GET_HOMOLOGUES manual

**Comment by eead-csic-compbio** [comment]
@vinuesa ?

**Comment by vinuesa** [comment]
Hi, you need to make sure that the FASTA labels are unique. I see from your output above, that [Planktothrix_tepida]PCC9214 & [Planktothrix_tepida_PCC_9214] seem to be the same strains/genomes. Could you send me an example file?
