### ISSUE TITLE
get_phylomarker error in test 21 and 22

### ISSUE THREAD

**Issue by 4br4ha4mRR** [vinuesa/get_phylomarkers#17]
Dear get_phylomarkers team,
 
When i run 

$ perl test_get_phylomarkers.t

I am getting the following error in test 21 and 22 only :

ok 20 - run_get_phylomarkers_pipeline.sh -R 1 -t PROT -A F ...
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
not ok 21 - run_get_phylomarkers_pipeline.sh -R 2 -t DNA -S K2P -k 1.3 -I 2
#   Failed test 'run_get_phylomarkers_pipeline.sh -R 2 -t DNA -S K2P -k 1.3 -I 2'
#   at test_get_phylomarkers.t line 83.
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
not ok 22 - run_get_phylomarkers_pipeline.sh -R 2 -t DNA -A F -k 1.2
#   Failed test 'run_get_phylomarkers_pipeline.sh -R 2 -t DNA -A F -k 1.2'
#   at test_get_phylomarkers.t line 86.
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
ok 23 - estimate_pangenome_phylogenies.sh -r 2 -S UFBoot ... [libnw.so]
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
the seq_key is 0000000000
the seq_key is 0000000000
the seq_key is 0000000001
the seq_key is 0000000002
the seq_key is 0000000003
the seq_key is 0000000003
the seq_key is 0000000004
the seq_key is 0000000005
the seq_key is 0000000005
the seq_key is 0000000006
the seq_key is 0000000006
the seq_key is 0000000007
the seq_key is 0000000008
the seq_key is 0000000008
the seq_key is 0000000009
the seq_key is 0000000009
the seq_key is 0000000010
the seq_key is 0000000010
the seq_key is 0000000011
the seq_key is 0000000011
ok 24 - estimate_pangenome_phylogenies.sh -c PARS -R 3 ...
# Looks like you failed 2 tests of 24.
make: *** [Makefile:6: test] Error 2

thanks

**Comment by 4br4ha4mRR** [comment]
Hi, thanks for your time
I have Ubuntu 24.04 LTS with GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu) installed.
pgrep -V prints me pgrep from procps-ng 4.0.4

**Comment by brunocontrerasmoreira** [comment]
Hello again @4br4ha4mRR , 
I have done some code edits and tests and can confirm that all tests included in `make clean test` work in my Ubuntu 20.04. Can you please try again?
You would need to
 - `git pull`
 - `make install` if you havent't done it yet
 - `make clean test`

**Comment by 4br4ha4mRR** [comment]
Hello @brunocontrerasmoreira,

I was able to solve it by changing in the script test_get_phylomarkers.t the grep command to pgrep -f in line 83 and 86. Maybe it could be the version of bash in Ubuntu 24.04. Thank you very much for your answer.  
Regards

**Comment by vinuesa** [comment]
build passing.
