### ISSUE TITLE
ERROR: Input f?aed files do not contain the same number of strains and a single instance for each strain...

### ISSUE THREAD

**Issue by kuzman1306** [vinuesa/get_phylomarkers#4]
Dear get_phylomarkers team,

I attempted to use get_phylomarkers pipeline in a  Docker environment (DockerToolbox-18.09.3). I tried to test it with provided dataset test_sequences/core_genome, but getting the error message (log file attached). I wonder if you could help me with this issue.

I look forward to hearing from you.

Sincerely,

Nemanja

[ERROR.log](https://github.com/vinuesa/get_phylomarkers/files/3393353/ERROR.log)

**Comment by vinuesa** [comment]
Hi Nemanja,

yes, I noticed from the logfile you sent earlier that you were running a docker container
instance. What is your host machine's OS and version?

I'd like to be sure that you followed the instructions provided here:

https://github.com/vinuesa/get_phylomarkers/blob/master/docs/GET_PHYLOMARKERS_manual.md#how-to-share-data-between-the-host-your-machine-and-the-get_homologues--get_phylomarkers-docker-container

which indicate how to share data between the host (your) machine and the GET_HOMOLOGUES +
GET_PHYLOMARKERS Docker container. Pay particular attention to points 2,3 and 4.

If you did so, could you please provide me with the output of points 5.3 and 6.1.
and that of the following lines of the tutorial:

# assumes that you are within test_sequences/pIncAC_homologues/ or in test_sequences/core_BCM
cd core_BCM

# 1. make sure we have the same nuber of faa and fna cluster files;
#    Note that GET_PHYLOMARKERS will check that for you automatically ;)
find . -name '*.faa' | wc -l  # 31
find . -name '*.fna' | wc -l  # 31

# 2.1 view the help menu of the main script
run_get_phylomarkers_pipeline.sh
run_get_phylomarkers_pipeline.sh -h

# 2.2 run the pipeline under default values. See the manual for the many additional options
run_get_phylomarkers_pipeline.sh -R 1 -t DNA -D -V

That would help us diagnose the problem.

Thanks for your patience and support!

**Comment by kuzman1306** [comment]
Dear Pablo,

Thank you for your quick answer.

My host machine's OS is Windows 10 Home, Version 1809.

I followed all your instructions, but still getting the same error. Please find log files attached. The outputs of points 5.3 and 6.1. and that of the following lines of the tutorial are included there.

Just one more remark, when I used get_homologues, and compare_cluster with my own data, everything worked smoothly. 

Thank you very much for your effort.

I look forward to hearing from you.

Cheers,

Nemanja

[log.txt](https://github.com/vinuesa/get_phylomarkers/files/3398505/log.txt)
[log2.txt](https://github.com/vinuesa/get_phylomarkers/files/3398506/log2.txt)

**Comment by vinuesa** [comment]
As far as i can judge, there seems to be a problem with the directory permissions. Let us try to confirm this. Could you please start a new container,  issue the following commands and share the output?:
cd test_sequences/ && ls -l
cd test_sequences/ && ls -l

As you can see below, all directories should be writable by everyone (user, group and others)
$ cd test_sequences/ && ls -l
drwxrwxrwx 5 vinuesa vinuesa 4096 jul 15 15:08 test_sequences
$ cd  test_sequences/ && ls -l
total 12
drwxrwxrwx 4 vinuesa vinuesa 4096 jul 15 15:29 core_genome
drwxrwxrwx 2 vinuesa vinuesa 4096 jul 15 15:08 pan_genome
drwxrwxrwx 2 vinuesa vinuesa 4096 jul 15 15:08 pIncAC

Unfortunately, I do not have a Windows machine to run and test the docker image on that platform. I downloaded and setup the docker image on my Ubuntu box following the provided instructions, and had no problems. 

Just in case, try also running the image with the following command:
docker run --rm -it csicunam/get_homologues:latest /bin/bash

Please let me know if any of these instructions helped you identify and eventually fix the problem.
Cheers,
Pablo
