### ISSUE TITLE
get_phylomarkers_error

### ISSUE THREAD

**Issue by kuzman1306** [vinuesa/get_phylomarkers#6]
Dear get_phylomarkers team,

I am using the pipeline through the docker image. Scripts get_homologues and compare_clusters worked fine, but I am getting the following error with get_phylomarkers:

```
 >>>>>>>>>>>>>>> parallel IQ-TREE runs to estimate gene trees <<<<<<<<<<<<<<<

 >>> wrote file IQT_DNA_gene_tree_Tmedium_stats.tsv ...
 >>> wrote file iqtree_output_files.tgz ...
[02:15:46] # running compute_MJRC_tree treefile I ...
 >>> Wrote file IQT_MJRC_tree.nwk ...
[02:15:47] # counting branches on 619 gene trees ...
 >>> wrote file no_tree_branches.list ...

 >>>>>>>>>>>>>>> filter gene trees for outliers with kdetrees test <<<<<<<<<<<<<  <<

 >>> wrote file all_gene_trees.tre ...
[02:15:48] # running kde test ...

 ERROR: the expected outfile kde_dfr_file_all_gene_trees.tre.tab was not produce  d
            This may be because R package(s) kdetrees,ape are not properly insta  lled.
            Please run the script './install_R_deps.R' from within /get_phylomar  kers to install them.
            Further installation tips can be found in file Rscript install_R_dep  s.R

>
>        print("Your R installation currently searches for packages in :")
[1] "Your R installation currently searches for packages in :"
>        print(.libPaths())
[1] "/get_phylomarkers/lib/R"       "/usr/local/lib/R/site-library"
[3] "/usr/lib/R/site-library"       "/usr/lib/R/library"
>
```

I wonder if you could help me with this?

I look forward to hearing from you.

Sincerely,

Nemanja

**Comment by vinuesa** [comment]
Dear Nemanja,
according to the error message, it seems that the R interpretar cannot find the ape or kdetrees packages.

Could you please issue the following commands from an R console:
help(package="ape")
help(package="kdetrees")

These should display the corresponding help/manual pages. If they are not displayed, run the 
'./install_R_deps.R' script from within the  /get_phylomarkers distro folder to install them. That should have been automatically set up while installing the docker image. The problem may be at that level.
Please let us know if the problems persist.
Best,
Pablo

**Comment by kuzman1306** [comment]
Dear Pablo,

Thank you for your reply.

I am getting the following error:


you@dc77b071408e:/get_phylomarkers$ ./install_R_deps.R
Warning in install.packages(package, dependencies = TRUE, lib = local_lib,
 :
  'lib = "./lib/R"' is not writable
Error in install.packages(package, dependencies = TRUE, lib = local_lib,  :
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE,  :
  there is no package called ‘kdetrees’
Execution halted

Cheers,

Nemanja

**Comment by vinuesa** [comment]
Looks like docker configuration problem ... What is your host machine's OS?

**Comment by kuzman1306** [comment]
It is Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

**Comment by eead-csic-compbio** [comment]
Hi Nemanja, 
many thanks for pointing this up. We could confirm the error and have now rebuilt the docker image with R version 3.6.0 instead. It is at 

https://hub.docker.com/layers/csicunam
/get_homologues/10032020-10Jan20/images/sha256-b82e2d8ffa1e93739436b340a0a42f7d293c1743ef133f8d1c008f237786106c?context=explore

I have tested it and seems to work fine. Please let us know if you have trouble with it, thanks,
Bruno

**Comment by kuzman1306** [comment]
Dear Bruno,

I have tested the new version of the docker image and
run_get_phylomarkers_pipeline.sh works fine.

Thank you for your effort.

Cheers,

Nemanja
