### ISSUE TITLE
pan-genome phylogeny under the parsimony criterion with GET_PHYLOMARKERS

### ISSUE THREAD

**Issue by kuzman1306** [vinuesa/get_phylomarkers#8]
Dear GET_PHYLOMARKERS team,

I am suing docker image "10032020-10Jan20" on Ubuntu 18.04 LTS.
I successfully generated ML tree by using PGM as an input, but getting the following error with parsimony inference. Please see bellow the error.

```
you@13680c26d4a9:~/get_homPhy/v2_homologues/pan_CM_C90_COG_OMCL$ estimate_pangenome_phylogenies.sh -c PARS -R 3 -i pangenome_matrix_t0.phylip -n 28 -b 25 -j 10 -t 1

### estimate_pangenome_phylogenies.sh v.1.1_10Jan20 run on 2020_05_03-10.12.28 with the following parameters:
# topdir = /home/you/get_homPhy/v2_homologues/pan_CM_C90_COG_OMCL | criterion:PARS
# runmode = 3 | input_phylip = pangenome_matrix_t0.phylip | input_phylo =
# n_cores = 28 | bootstrap no. = 25 | n_jumbles_pars = 10 | t_jumbles_boot_pars = 1
# DEBUG=0

found dir boot_pars
should dir boot_pars be removed y|n? y
 ... working in dir full_pars
# running pars < pars.params &> /dev/null in run1
# running pars < pars.params &> /dev/null in run2
# running pars < pars.params &> /dev/null in run3
# running pars < pars.params &> /dev/null in run4
# running pars < pars.params &> /dev/null in run5
# running pars < pars.params &> /dev/null in run6
# running pars < pars.params &> /dev/null in run7
# running pars < pars.params &> /dev/null in run8
# running pars < pars.params &> /dev/null in run9
# running pars < pars.params &> /dev/null in run10
# running pars < pars.params &> /dev/null in run11
# running pars < pars.params &> /dev/null in run12
# running pars < pars.params &> /dev/null in run13
# running pars < pars.params &> /dev/null in run14
# running pars < pars.params &> /dev/null in run15
# running pars < pars.params &> /dev/null in run16
# running pars < pars.params &> /dev/null in run17
# running pars < pars.params &> /dev/null in run18
# running pars < pars.params &> /dev/null in run19
# running pars < pars.params &> /dev/null in run20
# running pars < pars.params &> /dev/null in run21
# running pars < pars.params &> /dev/null in run22
# running pars < pars.params &> /dev/null in run23
# running pars < pars.params &> /dev/null in run24
# running pars < pars.params &> /dev/null in run25
# running pars < pars.params &> /dev/null in run26
# running pars < pars.params &> /dev/null in run27
# running pars < pars.params &> /dev/null in run28
# waiting for pars jobs to finish ...
# working in /home/you/get_homPhy/v2_homologues/pan_CM_C90_COG_OMCL/boot_pars ...
/get_phylomarkers/bin/linux/.libs/lt-nw_reroot: error while loading shared libraries: libnw.so.0: cannot open shared object file: No such file or directory
/get_phylomarkers/bin/linux/.libs/lt-nw_reroot: error while loading shared libraries: libnw.so.0: cannot open shared object file: No such file or directory
/get_phylomarkers/bin/linux/.libs/lt-nw_support: error while loading shared libraries: libnw.so.0: cannot open shared object file: No such file or directory
awk: program limit exceeded: maximum number of fields size=32767
        FILENAME="pangenome_matrix_t0.tab" FNR=1 NR=1
the seq_key => seq_ID correspondences for aln pang_ID-Strain_corresp.tsv are:
0000000000 =>
0000000001 =>
0000000002 =>
0000000003 =>
0000000004 =>
0000000005 =>
0000000006 =>
0000000007 =>
0000000008 =>
0000000009 =>
0000000010 =>
0000000011 =>
0000000012 =>
0000000013 =>
0000000014 =>
0000000015 =>
0000000016 =>
0000000017 =>
0000000018 =>
0000000019 =>
0000000020 =>
0000000021 =>
0000000022 =>
0000000023 =>
0000000024 =>
0000000025 =>
0000000026 =>
0000000027 =>
0000000028 =>
0000000029 =>
0000000030 =>
0000000031 =>
0000000032 =>
0000000033 =>
0000000034 =>
0000000035 =>
0000000036 =>
0000000037 =>
0000000038 =>
0000000039 =>
0000000040 =>
0000000041 =>
0000000042 =>
0000000043 =>
0000000044 =>
0000000045 =>
0000000046 =>
0000000047 =>
0000000048 =>
0000000049 =>
0000000050 =>
0000000051 =>
0000000052 =>
0000000053 =>
0000000054 =>
0000000055 =>
0000000056 =>
0000000057 =>
0000000058 =>
0000000059 =>
0000000060 =>
0000000061 =>
0000000062 =>
0000000063 =>
0000000064 =>
0000000065 =>
0000000066 =>
0000000067 =>
0000000068 =>



 >>> ERROR! The expected output file full_pars_tree_rooted_withBoot.ph was not produced, will exit now!

```

I wonder if you could help me with this.

Cheers,

Nemanja

**Comment by vinuesa** [comment]
Dear Nemanja, I'm embarrassed for not having answered before. The '/get_phylomarkers/bin/linux/.libs/lt-nw_reroot: error while loading shared libraries: libnw.so.0' that you report is solved in the new [Docker image for GET_HOMOLOGUES+GET_PHYLOMARKERS](https://hub.docker.com/r/csicunam/get_homologues) released yesterday night , as well as in the new [GET_PHYLOMARKERS image](https://hub.docker.com/r/vinuesa/get_phylomarkers) and latest [GET_PHYLOMARKERS release on GitHub](https://github.com/vinuesa/get_phylomarkers/). With best regards, Pablo.

**Comment by kuzman1306** [comment]
Dear Pablo,

I finally tried the new docker image and estimate_pangenome_phylogenies.sh
v.1.2_16Sep21. I used the following command: estimate_pangenome_phylogenies.sh
-c PARS -R 3 -i pangenome_matrix_t0.phylip -n 28 -b 25 -j 10 -t 1 , but I
got the following error:

...
# working in /home/you/get_homPhy/directory/boot_pars ...
ERROR: missing ')' at line 677 near '('
WARNING: zero bipart count for
....................................................................................***********........................
awk: program limit exceeded: maximum number of fields size=32767
        FILENAME="pangenome_matrix_t0.tab" FNR=1 NR=1
the seq_key => seq_ID correspondences for aln pang_ID-Strain_corresp.tsv
are:
0000000000 =>
...

The folder boot_pars with output files was not created.

I wonder if you could help me here.

Best regards,

Nemanja

**Comment by eead-csic-compbio** [comment]
Hi @kuzman1306 , @vinuesa that looks like a file with too many columns for awk perhaps?

**Comment by vinuesa** [comment]
Hi @kuzman1306, v1.2_16Sep21 is a rather old version. If you look at the [tags](https://hub.docker.com/r/vinuesa/get_phylomarkers/tags), the latest one is 20220618. 

Could you please run 'docker pull vinuesa/get_phylomarkers:latest' to upgrade to v20220618?

As documented in the [get_phylomarkers' DockerHub page](https://hub.docker.com/r/vinuesa/get_phylomarkers), this version contains notable additions, most notably the addition of ASTRAL to compute a concatenation-independent species tree. 

That version passes all tests, including a parsimony run with bootstrapping on a pangenome matrix with estimate_pangenome_phylogenies.sh. 

Please let us know if you still encounter any problems.
